
import React, { useState, useRef } from 'react';
import { domToPng } from 'modern-screenshot';
import { Subscription, BASE_CURRENCY } from '../types';
import { calculateMonthlyCost } from '../utils/calculations';
import { formatCurrency } from '../utils/currency';
import { getCurrentDate } from '../utils/dateUtils';

interface ShareViewProps {
  subscriptions: Subscription[];
}

export const ShareView: React.FC<ShareViewProps> = ({ subscriptions }) => {
  const [sharerName, setSharerName] = useState('SubTracker 用户');
  const [avatar, setAvatar] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const posterRef = useRef<HTMLDivElement>(null);

  const aiSubscriptions = subscriptions.filter(s => 
    s.category.toLowerCase().includes('ai') || 
    ['chatgpt', 'claude', 'midjourney', 'perplexity', 'runway', 'suno', 'openai', 'deepseek', 'flux', 'kimi'].some(keyword => s.name.toLowerCase().includes(keyword))
  );

  const now = getCurrentDate();
  const monthlyCost = calculateMonthlyCost(subscriptions, now.getFullYear(), now.getMonth());

  const handleAvatarUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => setAvatar(event.target?.result as string);
      reader.readAsDataURL(file);
    }
  };

  const handleDownload = async () => {
    if (!posterRef.current) return;
    setIsGenerating(true);
    
    try {
      // 使用稳定版选项
      const dataUrl = await domToPng(posterRef.current, {
        scale: 2,
        backgroundColor: '#f8fafc',
        quality: 1,
      });

      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = `subtracker-ai-report-${Date.now()}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

    } catch (err) {
      console.error('Poster generation failed:', err);
      alert('海报生成失败，请尝试直接截屏分享。');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-12 pb-24 animate-in fade-in duration-500">
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-white p-8 rounded-[2rem] shadow-sm border border-slate-100 space-y-8">
            <div>
               <h2 className="text-xl font-black text-slate-900 tracking-tight mb-1">分享我的订阅清单</h2>
               <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest leading-relaxed">Generated by AI Smart Ledger</p>
            </div>
            
            <div className="space-y-6">
              <div className="space-y-1.5">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">展示昵称</label>
                <input 
                  value={sharerName}
                  onChange={(e) => setSharerName(e.target.value)}
                  className="w-full bg-slate-50 border-2 border-slate-50 focus:border-indigo-100 rounded-xl py-3.5 px-5 text-sm font-bold outline-none"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">头像</label>
                <div className="flex items-center gap-4">
                  <div className="w-14 h-14 rounded-full bg-slate-100 flex-shrink-0 overflow-hidden border-2 border-white shadow-sm">
                    {avatar ? <img src={avatar} className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center text-slate-300 font-black text-xl">?</div>}
                  </div>
                  <label className="flex-1 cursor-pointer bg-slate-50 hover:bg-slate-100 text-slate-600 px-4 py-2.5 rounded-xl text-[10px] font-black uppercase text-center border-2 border-dashed border-slate-200 transition-all">
                    更换头像
                    <input type="file" className="hidden" accept="image/*" onChange={handleAvatarUpload} />
                  </label>
                </div>
              </div>
            </div>

            <button 
              onClick={handleDownload}
              disabled={isGenerating}
              className="w-full py-4 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-200 text-white rounded-2xl font-black text-xs uppercase tracking-[0.2em] transition-all shadow-xl shadow-indigo-100/30 flex items-center justify-center gap-3 active:scale-95"
            >
              {isGenerating ? <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></span> : '生成海报'}
            </button>
          </div>
        </div>

        <div className="lg:col-span-8 flex justify-center">
          <div className="sticky top-28 w-full max-w-[400px]">
            <div 
              ref={posterRef}
              className="bg-white rounded-[2.5rem] shadow-2xl shadow-indigo-100/40 overflow-hidden w-full border border-slate-100 flex flex-col relative"
              style={{ minHeight: '560px' }}
            >
              <div className="p-10 bg-indigo-600 text-white">
                <div className="flex items-center gap-4 mb-10">
                  <div className="w-16 h-16 rounded-full border-4 border-white/20 shadow-xl overflow-hidden bg-white/5 backdrop-blur-sm">
                    {avatar ? <img src={avatar} className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center text-white/30 text-2xl font-black">?</div>}
                  </div>
                  <div>
                    <h3 className="text-xl font-black truncate max-w-[180px]">{sharerName}</h3>
                    <p className="text-[10px] font-black text-white/50 uppercase tracking-widest mt-1">Digital Subscriptions</p>
                  </div>
                </div>
                <div>
                  <p className="text-[9px] font-black uppercase tracking-[0.4em] text-white/40 mb-1">Monthly Cost</p>
                  <p className="text-5xl font-black tracking-tighter">{formatCurrency(monthlyCost, BASE_CURRENCY)}</p>
                </div>
              </div>

              <div className="flex-1 p-10 bg-slate-50 flex flex-col">
                <div className="flex-1 space-y-3">
                  {subscriptions.slice(0, 6).map((sub, idx) => (
                    <div key={idx} className="bg-white p-4 rounded-2xl border border-slate-100 flex items-center justify-between shadow-sm">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center border border-slate-100 text-indigo-600 font-black text-lg">
                           {sub.name.charAt(0)}
                        </div>
                        <div>
                          <p className="text-xs font-black text-slate-900 leading-tight">{sub.name}</p>
                          <p className="text-[8px] text-slate-400 font-bold uppercase tracking-widest mt-0.5">{sub.category}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-xs font-black text-slate-900">{formatCurrency(sub.cost, sub.currency)}</p>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-10 pt-6 border-t border-slate-200/60 flex items-end justify-between">
                  <div>
                    <p className="text-sm font-black text-slate-900 tracking-tighter">SubTracker AI</p>
                    <p className="text-[7px] font-bold text-slate-400 uppercase tracking-widest mt-1">Smart Ledger Generation</p>
                  </div>
                  <div className="text-right">
                    <p className="text-[9px] font-black text-indigo-600 uppercase tracking-widest">My Report</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
